name: readr_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# iOS and android is the same version
# version: 3.0.0+314
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # http ajax call
  http: ^0.12.2
  # launching a URL in the mobile platform
  url_launcher: ^5.7.2
  # webview
  webview_flutter: ^1.0.1
  # local storage
  localstorage: ^3.0.2+5
  # A Flutter plugin to store data in secure storage
  flutter_secure_storage: ^3.3.5
  # drag and drop object
  reorderables: ^0.3.2
  # A mixture between dependency injection (DI) and state management
  provider: ^4.1.0
  #get: ^2.7.1
  # cached network image
  cached_network_image: ^2.2.0+1
  # share url
  share: ^0.6.3+5
  # A Flutter widget that scrolls text infinitely.
  marquee: ^1.5.2
  # carousel slider in flutter
  carousel_slider: ^2.3.1
  # widget from html
  flutter_widget_from_html: ^0.5.0+7
  # video player
  video_player: ^0.10.11+2
  # a friendly Material or Cupertino UI for video
  chewie: ^0.9.10
  # audio service
  audioplayers: ^0.15.1
  # spin
  flutter_spinkit: ^4.1.2+1
  # flutter cache manager
  flutter_cache_manager: ^1.4.2
  # package for working with MIME type definitions
  mime: ^0.9.7
  # app link
  uni_links: ^0.4.0
  
  # appsflyer
  appsflyer_sdk: ^6.0.5
  
  # force app to upgrade
  upgrader: ^2.6.1
  # android in app update
  in_app_update: ^1.1.13
  # get package info 
  package_info: ^0.4.3
  # version class
  version: ^1.2.0
  
  # firebase
  firebase_core: ^0.5.2+1
  # firebase messaging
  firebase_messaging: ^7.0.3
  # firebase ad mob
  firebase_admob: ^0.10.2
  #flutter_native_admob: ^2.1.0+3
  admob_flutter: ^1.0.0
  # firebase dynamic links 
  firebase_dynamic_links: ^0.6.2

  # firebase auth
  firebase_auth: ^0.18.3+1
  # google sign in
  google_sign_in: ^4.5.6

  # generate app icons
  flutter_launcher_icons: ^0.7.5

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/icon.jpg
    - assets/image/google_icon.png
    - assets/image/wine_warning.png
    - assets/data/countries.json
    - assets/data/taiwanDistricts.json
    - assets/data/records.json
    - assets/data/menu.json
    - assets/data/defaultNotificationList.json
    # section ad data
    - assets/data/iOSTestSectionAd.json
    - assets/data/iOSSectionAd.json
    - assets/data/androidTestSectionAd.json
    - assets/data/androidSectionAd.json
    # story ad data
    - assets/data/iOSTestStoryAd.json
    - assets/data/iOSStoryAd.json
    - assets/data/androidTestStoryAd.json
    - assets/data/androidStoryAd.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
