name: readr_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# iOS and android is the same version






version: 6.9.25+475


environment:
  sdk: '>=2.12.0 <=3.4.4'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_storage: ^2.1.1
  sprintf: ^7.0.0
  json_annotation: ^4.8.1
  graphql_flutter: ^5.1.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  youtube_player_flutter: ^8.1.2
  # being able to compare objects 
  equatable: ^2.0.3
  # http ajax call
  http: ^1.0.0
  # launching a URL in the mobile platform
  url_launcher: ^6.0.18
  # blocs and cubits.
  flutter_bloc: ^8.0.1
  # toast Library for Flutter
  fluttertoast: ^8.0.8
  # webview
  webview_flutter: ^4.7.0
  # mirrormedia embedded code

  flutter_embedded_webview:
    git:
      url: https://github.com/mirror-media/flutter_embedded_webview.git
      ref: master
      version: ^0.6.2
  # local storage
  localstorage: ^4.0.0+1
  # A Flutter plugin to store data in secure storage
  flutter_secure_storage: ^9.0.0
  # drag and drop object
  reorderables: ^0.5.0
  # automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^3.0.0
  # cached network image
  cached_network_image: ^3.2.0
  # share url
  share_plus: ^10.0.2
  # A Flutter widget that scrolls text infinitely.
  marquee: ^2.2.0
  # carousel slider in flutter
  carousel_slider: ^4.0.0
  # widget from html
  flutter_widget_from_html: ^0.15.2
  # video player
  video_player: ^2.2.11
  # a friendly Material or Cupertino UI for video
  chewie: ^1.2.2
  # audio service
  audioplayers: ^5.2.1
  # spin
  flutter_spinkit: ^5.1.0
  # flutter cache manager
  flutter_cache_manager: ^3.3.0
  # package for working with MIME type definitions
  mime: ^1.0.1
  # app link
  uni_links: ^0.5.1
  # mirrormedia constants
  constants:
    git:
      url: https://github.com/mirror-media/constants.git
      ref: master
      version: ^2.0.0
  # custom real time invoice widget
  real_time_invoice_widget:
    git:
      url: https://github.com/mirror-media/RealTimeInvoiceWidget.git
      ref: main
      version: ^1.0.9+9


  # android in app update
  in_app_update: ^4.2.3
  # get package info 
  package_info_plus: ^8.0.1
  # display ios 14+ tracking authorization dialog and request permission to collect data.
  app_tracking_transparency: ^2.0.2+1
  # version class
  version: ^3.0.2
  firebase_core_platform_interface: ^5.0.0
  # firebase
  firebase_core: ^3.3.0
  # firebase analytics API
  firebase_analytics: ^11.3.0
  # firebase messaging
  firebase_messaging: ^15.0.4
  # firebase remote config
  firebase_remote_config: ^5.0.4
  google_mobile_ads: ^5.1.0

  # firebase crashlytics
  firebase_crashlytics: ^4.0.4

  # firebase auth
  firebase_auth: ^5.2.0
  # google sign in
  google_sign_in: ^5.2.2
  # facebook sign in
  flutter_facebook_auth: ^6.2.0
  # apple sign in
  sign_in_with_apple: ^4.1.0

  # a storefront-independent API for purchases in Flutter apps.
  in_app_purchase: ^3.0.2

  # generate app icons
  flutter_launcher_icons: ^0.10.0

  # more powerful webview
  flutter_inappwebview: ^5.5.0+2

  # zoomable widget
  photo_view: ^0.14.0
  # svg loader
  flutter_svg: ^2.0.10+1

  audio_session: ^0.1.18
  
  file: ^6.1.2
  intl: ^0.19.0
  get: ^4.6.3
  visibility_detector: ^0.3.3
  percent_indicator: ^4.2.2

  #format css
  csslib: ^0.17.1

  bloc: ^8.1.1
  meta: ^1.8.0
  device_info_plus: ^9.1.1
  in_app_purchase_storekit: ^0.3.6+3
  upgrader: ^10.3.0
  firebase_dynamic_links: ^6.0.4
dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  # generate splash screen
  flutter_native_splash: ^2.2.0+1
  # generated mock classes
  mockito: ^5.0.17
  
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/icon.jpg
    - assets/image/facebook_icon.png
    - assets/image/google_icon.png
    - assets/image/apple_icon.png
    - assets/image/wine_warning.png
    - assets/image/ig_icon.png
    - assets/image/line_icon.png
    - assets/image/yt_icon.png
    - assets/image/mm_logo_for_story.png
    - packages/constants/countries.json
    - packages/constants/taiwan-districts.json
    - assets/data/menu.json
    - assets/data/defaultNotificationList.json
    - assets/image/podcast/play_icon.png
    - assets/image/podcast/stop_icon.png
    - assets/image/podcast/podcast_panel_play_icon.png
    - assets/image/podcast/podcast_panel_stop_icon.png
    - assets/image/podcast/volume.png
    - assets/image/podcast/volume_mute.png

    # section ad data
    - assets/adJson/dev/iOSSectionAd.json
    - assets/adJson/prod/iOSSectionAd.json
    - assets/adJson/dev/androidSectionAd.json
    - assets/adJson/prod/androidSectionAd.json
    # story ad data
    - assets/adJson/dev/iOSStoryAd.json
    - assets/adJson/prod/iOSStoryAd.json
    - assets/adJson/dev/androidStoryAd.json
    - assets/adJson/prod/androidStoryAd.json
    # magazine image
    - assets/image/splash.png
    - assets/image/premiumIcon.png
    - assets/image/premiumText.png
    - assets/image/magazine/magazineDownloadIcon.png
    - assets/image/magazine/hami.png
    - assets/image/magazine/kono.png
    - assets/image/magazine/my_book.png
    - assets/image/magazine/pubu.png
    - assets/image/magazine/readmoo.png
    - assets/image/magazine/book_icon.svg
    # member subscription
    - assets/image/badge.png
    - assets/image/member/subscription_icon.png
    - assets/image/member/subscribe_banner_mobile.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
